language: php

php:
  - 5.6
  - 7.0
  - 7.1

sudo: false

services:
  - memcached
  - redis-server

before_install:
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update
  - travis_retry composer install

script: phpunit

matrix:
  allow_failures:
    - php: 5.6